---
- name: Ensure autofs and PAM packages installed
  package:
    name:
      - autofs
      - libpam-modules
    state: present

- name: Configure auto.master.d entries
  copy:
    dest: /etc/auto.master.d/filestore.autofs
    content: |
      /home   /etc/auto.home
      /shared /etc/auto.shared
  notify: restart autofs

- name: Configure auto.home to map per-user homes
  copy:
    dest: /etc/auto.home
    content: |
      * -rw,soft,intr {{ filestore_ip }}:/export/home/&
  notify: restart autofs

- name: Configure auto.shared
  copy:
    dest: /etc/auto.shared
    content: |
      data     -rw,soft,intr {{ filestore_ip }}:/export/shared/data
      projects -rw,soft,intr {{ filestore_ip }}:/export/shared/projects
      models   -rw,soft,intr {{ filestore_ip }}:/export/shared/models
  notify: restart autofs

- name: Ensure /shared exists
  file:
    path: /shared
    state: directory
    mode: '0755'

- name: Enable pam_mkhomedir for session
  lineinfile:
    path: /etc/pam.d/common-session
    line: 'session required pam_mkhomedir.so skel=/etc/skel/ umask=0022'
    state: present
    insertafter: EOF
  when: ansible_facts.os_family == 'Debian'

