---
- name: Ensure baseline packages are installed
  apt:
    name:
      - python3
      - python3-pip
      - git
      - tmux
      - htop
      - unzip
      - curl
      - jq
      - nfs-common
      - autofs
      - openssh-client
      - libpam-modules
    state: present
    update_cache: true

- name: Install Google Ops Agent
  shell: |
    curl -sS https://dl.google.com/cloudagents/add-google-cloud-ops-agent-repo.sh | bash -s -- --also-install
  args:
    creates: /etc/google-cloud-ops-agent/config.yaml

- name: Harden SSH - disable root login and password auth
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^{{ item.key }}"
    line: "{{ item.key }} {{ item.value }}"
    state: present
    backrefs: yes
  loop:
    - { key: 'PermitRootLogin', value: 'no' }
    - { key: 'PasswordAuthentication', value: 'no' }
  notify: Restart ssh

- name: Ensure ansible_ready marker exists
  file:
    path: /var/tmp/ansible_ready
    state: touch


